//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Admin
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Required")]
        public string EmployeeName { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Client { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Amount { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "Required")]
        public string PurchasedItem { get; set; }

        [Required(ErrorMessage = "Required")]
        public string Bill { get; set; }
     
    }

}
